@echo off
echo Copying php.ini ...
xcopy winConfig\php.ini ..\..\..\php\ /Y
echo Copying sendmail.ini ...
xcopy winConfig\sendmail.ini ..\..\..\sendmail\ /Y
echo Copying Apache server settings ...
xcopy svrConfig\httpd.conf ..\..\..\apache\conf /Y
echo Copying mySQL settings ...
xcopy svrConfig\my.ini ..\..\..\mysql\bin /Y
echo Copying DB data ...
xcopy ..\data ..\..\..\mysql\ /Y
echo Done!
PAUSE
